import { readFileSync } from 'node:fs';
import path from 'node:path';

const POSTS_PATH = path.join(process.cwd(), 'content/blog/posts.json');

// content/blog/posts.json is generated by scripts/fetchBuildTimeContent.mjs
// (the `prebuild` step) and gitignored. Falls back to an empty list if it
// doesn't exist yet (e.g. local dev without BASE44_API_KEY) so the build
// doesn't crash — it will simply produce zero blog pages in that case.
function loadPosts() {
  try {
    const raw = readFileSync(POSTS_PATH, 'utf-8');
    return JSON.parse(raw);
  } catch {
    return [];
  }
}

// `topic_segment` can be an empty string in the real BlogPost data. An empty
// string produces an empty URL segment, which Next.js's static export
// rejects outright — surfacing as the misleading "missing
// generateStaticParams()" build error instead of anything about the empty
// segment itself (confirmed by reproducing locally: a single post with
// topic_segment: "" is enough to trigger it). This fallback is ONLY for the
// routing/URL segment value — the underlying topic_segment field itself is
// left untouched for display/metadata use. Used identically in both
// generateStaticParams() and the lookup below so the generated route and
// the post it resolves to always agree.
function topicUrlSegment(post) {
  return post.topic_segment || 'allgemein';
}

export async function generateStaticParams() {
  const posts = loadPosts();
  if (posts.length === 0) {
    // With `output: 'export'`, Next.js requires at least one static param
    // per dynamic route or the build fails outright. This placeholder keeps
    // the build green when there are zero published posts (fresh site,
    // local dev without BASE44_API_KEY, or a build that happens to run
    // before the first post goes live) — it resolves to the "not found"
    // branch in the component below, never real content.
    return [{ source: '_none', target: '_none', topic: '_none', slug: '_none' }];
  }
  return posts.map((post) => ({
    source: post.source_language,
    target: post.target_language,
    topic: topicUrlSegment(post),
    slug: post.slug,
  }));
}

export default async function BlogPostPage({ params }) {
  // Next.js 15+/16: `params` is a Promise in Server Components and must be
  // awaited — reading properties off it directly (as this previously did)
  // silently yields `undefined` for every field, so no post ever matched
  // and every generated page rendered "Beitrag nicht gefunden", regardless
  // of topic_segment. Caught while verifying the topic_segment fallback
  // above against real matching data.
  const resolvedParams = await params;
  const posts = loadPosts();
  const post = posts.find(
    (p) =>
      p.source_language === resolvedParams.source &&
      p.target_language === resolvedParams.target &&
      topicUrlSegment(p) === resolvedParams.topic &&
      p.slug === resolvedParams.slug,
  );

  if (!post) {
    return (
      <main>
        <h1>Beitrag nicht gefunden</h1>
      </main>
    );
  }

  return (
    <main>
      <article>
        <h1>{post.title}</h1>
        <div dangerouslySetInnerHTML={{ __html: post.content }} />
      </article>
    </main>
  );
}
