import { readFileSync } from 'node:fs';
import path from 'node:path';

const POSTS_PATH = path.join(process.cwd(), 'content/blog/posts.json');

// content/blog/posts.json is generated by scripts/fetchBuildTimeContent.mjs
// (the `prebuild` step) and gitignored. Falls back to an empty list if it
// doesn't exist yet (e.g. local dev without BASE44_API_KEY) so the build
// doesn't crash — it will simply produce zero blog pages in that case.
function loadPosts() {
  try {
    const raw = readFileSync(POSTS_PATH, 'utf-8');
    return JSON.parse(raw);
  } catch {
    return [];
  }
}

export async function generateStaticParams() {
  const posts = loadPosts();
  if (posts.length === 0) {
    // With `output: 'export'`, Next.js requires at least one static param
    // per dynamic route or the build fails outright. This placeholder keeps
    // the build green when there are zero published posts (fresh site,
    // local dev without BASE44_API_KEY, or a build that happens to run
    // before the first post goes live) — it resolves to the "not found"
    // branch in the component below, never real content.
    return [{ source: '_none', target: '_none', topic: '_none', slug: '_none' }];
  }
  return posts.map((post) => ({
    source: post.source_language,
    target: post.target_language,
    topic: post.topic_segment,
    slug: post.slug,
  }));
}

export default function BlogPostPage({ params }) {
  const posts = loadPosts();
  const post = posts.find(
    (p) =>
      p.source_language === params.source &&
      p.target_language === params.target &&
      p.topic_segment === params.topic &&
      p.slug === params.slug,
  );

  if (!post) {
    return (
      <main>
        <h1>Beitrag nicht gefunden</h1>
      </main>
    );
  }

  return (
    <main>
      <article>
        <h1>{post.title}</h1>
        <div dangerouslySetInnerHTML={{ __html: post.content }} />
      </article>
    </main>
  );
}
